---
apiVersion: v1
kind: Service
metadata:
  name: controller-app-lb
  labels:
    app: controller-app
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: http
      targetPort: 80
  selector:
    app: controller-app
    version: v1
